// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "Home": {
      "title": "مرحبًا بك في سيتي بالس",
      "subtitle": "ابحث عن الفعاليات حولك"
    },
    "Auth": {
      "login": "تسجيل الدخول",
      "signup": "إنشاء حساب",
      "email": "البريد الإلكتروني",
      "password": "كلمة المرور"
    }
  };
export default messages;